language: c++
branches:
  only:
  - master
cache:
  ccache: true
  directories:
   - deno2/js/node_modules/
   - $DEPOT_TOOLS_PATH
   - $BUILD_PATH
env:
  global:
    - BUILD_PATH=$HOME/out/Default
    - DEPOT_TOOLS_PATH=$HOME/depot_tools
before_install: |
  if ! [ -x $DEPOT_TOOLS_PATH/gclient ]; then
    rm -rf $DEPOT_TOOLS_PATH
    git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $DEPOT_TOOLS_PATH
  fi
install:
 - unset CC CXX
 - export PATH=$PATH:$DEPOT_TOOLS_PATH
 - cd deno2
 - gclient sync --no-history
 # ccache needs this
 - export CCACHE_CPP2=yes
 - export CCACHE_SLOPPINESS=time_macros
 - export PATH=`pwd`/third_party/llvm-build/Release+Asserts/bin:$PATH
 - (cd js; yarn)
 - rm -f $BUILD_PATH/args.gn # Don't use cached values.
 - gn gen $BUILD_PATH --args='is_debug=false cc_wrapper="ccache" use_custom_libcxx=false use_sysroot=false'
 - gn args $BUILD_PATH --list
 - ccache -s
 - env
 - ninja -j2 -C $BUILD_PATH mock_runtime_test deno
script:
 - $BUILD_PATH/mock_runtime_test
 - $BUILD_PATH/deno
